name: Build TWRP for citrine

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
    - name: Build TWRP
      uses: azwhikaru/action-twrp-builder@main
      with:
        MANIFEST_BRANCH: twrp-12.1
        DEVICE_TREE: https://github.com/EAGLECOINPREMUIN/android_device_xiaomi_citrine
        DEVICE_TREE_BRANCH: main
        DEVICE_NAME: citrine
        MAKEFILE_NAME: twrp_citrine
        BUILD_TARGET: vendorboot
